; standalone configuration
[PORTS]
talkport=777

[ENV]
root=""; Where the root directory is located. Empty because of standalone version.
accept_cidr_range="192.168.0.0/32"; Accepted IP range, based on a CIDR mask. Other IPs contacting the Mule will have no response and a dead hanging socket.

[STORAGE]
mounts_path="/srv/mount/"; Where to apply relative volume mounting from
images_path="/srv/images/"; Image superfolder (can be several layers on top of actual .img files) to store volumes (used by mounts_path to reproduce file tree)
export_range="192.168.1.0/24"; NFS export range (visibility)
nfs="true"; Enables NFS and writes routes automatically when a new XFS disk is created
mount_options="loop,pquota"; Mount options for dynamically created volumes